[project]
name = "hybrid-recommender-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "snehav", email = "snehavreddy12@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "category-encoders>=2.11.1",
    "dask[dataframe]>=2026.8.0",
    "dvc[s3]>=3.67.1",
    "ipykernel>=7.4.0",
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "requests>=2.34.2",
    "scikit-learn>=1.9.1",
    "seaborn>=0.13.2",
    "streamlit>=1.65.0",
]

[project.scripts]
hybrid-recommender-system = "hybrid_recommender_system:main"

[build-system]
requires = ["uv_build>=0.12.11,<0.13.0"]
build-backend = "uv_build"
